[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/"
]

# Solidity version and optimizer
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# Directory settings
test = "test"
script = "script"
cache_path = "cache_forge"
broadcast = "broadcast"

# See more config options https://book.getfoundry.sh/reference/config
[rpc_endpoints]
sepolia = "${NEXT_PUBLIC_SEPOLIA_RPC_URL}"
mainnet = "https://mainnet.infura.io/v3/${NEXT_PUBLIC_INFURA_PROJECT_ID}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }